### ISSUE TITLE
Paragraph tagging?

### ISSUE THREAD

**Issue by OfficePop** [BeipDev/BeipMU#1]
Hey there!

I am wondering if Beip has any way to detect things like spaces and tags in text from commands such pose or @emit and automatically add the relevant mushcode tags (%R and %T) so that you can just drop your stuff into the input window without having dress it up with any formatting. What would it take to do this otherwise?

Just curious, thanks!

**Comment by BeipDev** [comment]
For anyone reason this... the issues was discussed and implemented on the reddit group: https://www.reddit.com/r/BeipMU/comments/7cl36v/autoformatting_for_paragraphs_and_tabs/ All good now!
