### ISSUE TITLE
/wall doesn't process aliases or /commands

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#100]
I have some aliases of /<command> (and have to send them with //, another minor complaint I can ignore for now) but /wall doesn't appear to use them when sending its commands. It also doesn't process other /commands like /receive. Attempting to use these returns the "Huh?" error from all connected worlds.

**Comment by BeipDev** [comment]
So you basically want /wall <text> to act like <text> was typed in every connected window?

**Comment by Seraphiel0** [comment]
I thought it was supposed to, and that it didn't was a bug. If it's an enhancement that's fine, too, it just seems more intuitive that it would work like this. This also shouldn't have any impact on anyone using it the other way either.
