### ISSUE TITLE
Shortcut to name highlight triggers

### ISSUE THREAD

**Issue by DeerInHeadlights2** [BeipDev/BeipMU#101]
Mushclient has a nice feature for non-power users that they can highlight a word, right click and there is a "highlight" option that basically makes them a trigger that colors the word some standard color.

I know it's not much work to create the triggers normally, but I suspect many users never even open a client's trigger screen. So it would be a nice ease-of-use feature to have. I helped a friend who uses Mushclient and it was much easier to walk her through it (highlight it, right click, there you go) than it would be walking her through trigger creation.

I like that BeipMU currently copies to clipboard what you highlight in an Output window on its own, which this feature would conflict with.  So maybe for this... first you right click on the Output Window and select a new "select word(s) for highlighting" choice.  Once they do the cursor changes color or something and they highlight the word.  When done, then make the trigger for them and pop open the Trigger Options to it, on the Appearance tab with Change Foreground pre-selected, and open the Foreground color selection tool so they can pick the color.

That way they get to pick the highlight color themselves.  Plus they'll be staring at the Trigger menu and maybe get the idea to start playing with triggers and getting even more out of BeipMU.

**Comment by BeipDev** [comment]
We had an idea about that today... using the new 'Hash' color. Basically select a word in the output, right click and say 'Add Color Trigger' and it'll add a new trigger that hash colors that text.

Though.. it's still not super discoverable as you have to select then right click without releasing left click. (or pause first). You can think about it... we could also just easily add a command for people to type (which is easy to paste from a web page)
