### ISSUE TITLE
Enh: Rt-click on tab shows name of active log, clicking on that presents rename dialog

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#102]
If I want to give a log file a more relevant name than the auto-generated date, I need to stop logging, go find the correct file, rename it, then manually resume logging. This is because the beip process has the file locked. Having beip do the renaming might be faster anyway.

**Comment by BeipDev** [comment]
I could change the sharing mode when logging to add 'FILE_SHARE_DELETE' which lets you delete/rename the log file while it's open. I don't really want to let people delete their log files, but it does let you rename them and I can handle the error after deleting pretty easily.

I could also have a 'Go to log file folder' option in the right click of a tab that's logging. Would that be a useful one too?

**Comment by Seraphiel0** [comment]
That sounds like it would address some of the root problem, sure. I thought it might be easier to invoke some pre-existing rename dialog so that beip automatically updates the name of the log it should be adding to, but if it's easier to do it this way then that's fine. :)

**Comment by BeipDev** [comment]
Are you changing the auto generated filename + date to something that couldn't be autogenerated?

Maybe editing the logging filename field should do an auto rename if it's currently logging?

**Comment by Seraphiel0** [comment]
Yeah I'm changing it to something with more context (Scene with so-and-so, Event blah, stuff like that) so there's no way that could auto-gen. My thinking was, the autogen works fine for any random day but if I end up doing something more noteworthy or that I expect to refer to again directly, I want to rename it so I can actually find it without having to do a search.

Editing the filename from within beip would be what I'm asking for, so the app renames it and continues logging in the new name.
