### ISSUE TITLE
HTML log format does not match screen output (indents, bubbles)

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#103]
"NinjakittenYesterday at 9:14 PM
nods
Well, the way to write them out is to have each pose be its own \<p\> and do \<p style="text-indent: 3em"\> on them. Or similar, you'd probably want to set the indent to whatever the user had it set as on their screen."

NinjakittenYesterday at 9:15 PM
(I am assuming the logs don't start with a block of css styling, though if they do then I'd put the text-indent just on p up at the top)
So there you go, @Bennet , that's how :wink:
(Also if each is its own \<p\> you can easily enough do your bubbles too.)
BennetYesterday at 11:17 PM
So what's the codes to do the bubbles?
NinjakittenYesterday at 11:23 PM
Well, depends just how someone has it set up, but like for my text messages from me to someone else, it'd be \<p style="background-color: rgb(188,235,194); border: 1px solid black; border-radius: .5em; color: black; float: left; margin: 6px 0; padding: 10px; width: 80%;"\>Stuff\</p\>

**Comment by BeipDev** [comment]
Finally got back to this.. worked with NK to get it very accurate. Hard to tell what's browser vs client

**Comment by BeipDev** [comment]
Fixed in 307
