### ISSUE TITLE
Pipe more type functionality?

### ISSUE THREAD

**Issue by Bieeanda** [BeipDev/BeipMU#104]
I think I asked about this on the Yahoo! group years ago, but I thought I'd ask again. Would it be possible to add (or script) a function to automatically pause the incoming window scroll like the 'more' command in Windows and *NIX?
I'm -still- using a registered version of SimpleMU because I haven't found another client that performs similarly.

**Comment by BeipDev** [comment]
Ah, I remember people asking about that a long time ago. Have you seen what was added in the last few months? There's a 'New Activity' indicator that shows what wasn't seen (not a 'more' one, but it's similar to what Discord has)

**Comment by Bieeanda** [comment]
Not recently, but I will, thanks! That sort of marker definitely helps; I just have a mild allergy to using my PgUp key for some reason.

**Comment by BeipDev** [comment]
Now that we have a Windows store version it's very easy to install and test and remove if you don't like it. Oh! And you can always redefine the 'page up' key to something else if you really hate that one particular key (hehe)

**Comment by BeipDev** [comment]
Was there anything more I can do on this issue or is it okay to close it?

**Comment by Bieeanda** [comment]
Go ahead, I've got used to how BeipMU does this sort of thing. Thanks again. :)

**Comment by BeipDev** [comment]
Cool, closing!
