### ISSUE TITLE
[Bug] Crash On Game Connect After Closing a Window.

### ISSUE THREAD

**Issue by RockyCoon** [BeipDev/BeipMU#106]
Here's What's Going On. First!

* I Use Windows 10 
* I use the download version from GitHub
* I am using the 64 Bit Version of The Current Latest Release. (4.00.284)
* I have eleven windows open when I do this, though it seems to do it when I have less than that open too.

Now Onto the Specifics

I have it set so it auto opens the characters I wanna have connected I usually do when I first connect onto games for the day/evening. That's about 11 windows on various MU*s. When I close one of these windows, and then, try to connect into a new window, the program hangs for a split second, then closes completely. 

That's about it.

**Comment by BeipDev** [comment]
Aha, I've tried to make this crash happen before but I never could. The other user that reported it said it was very sporadic. Does it happen reliably for you?

**Comment by RockyCoon** [comment]
Yup. Always happens when I do it.

**Comment by BeipDev** [comment]
Is there any chance you can get a minidump of the crash? (To generate crash minidumps - https://blogs.msdn.microsoft.com/chaun/2013/11/12/steps-to-catch-a-simple-crash-dump-of-a-crashing-process/ (steps on how to install Microsoft Debug Diagnostic tool, or use the built in WER system).

**Comment by BeipDev** [comment]
Also, are you on Discord? I want to help figure out how this is crashing, so let me know!

**Comment by RockyCoon** [comment]
Right, So. You're not gonna believe this B.S. :-/. I suddenly can't replicate it. I dunno what happened.  This is a bug I've had problems with for a long time--- But... I can open windows now after closing one? Without the slight hang and crash? I installed the debug program, went to go replicate the bug and I just can't do it anymore. I uninstalled the debug program just in case that was 'fixing' it and.. nope. It won't crash. :-/. And the only recent Windows Updates I can find in that time period are Windows Defender Definition Updates so I don't think anything was 'pushed' to fix it. 

If it starts happening again, I'll get a crash dump ASAP, but right now... seems to be working as intended now. z.z

**Comment by RockyCoon** [comment]
...and right after this I got it to happen again. Re-installing the Debug Tool I just uninstalled to test. :I. Will Edit this post momentarily.

**Comment by BeipDev** [comment]
Haha, it's all good. That's why when you said it was happening a lot I was like.. finally! Someone who can make it happen! Nobody's been able to make this happen in "captivity" yet.

We'll figure it out eventually!

**Comment by BeipDev** [comment]
After getting the crash info (Thanks to RockyCoon!) this crash was due to some unprotected script functions acting on a deleted object. Simple fix, it'll be in the next beta.
