### ISSUE TITLE
Auto-reconnect on network failure

### ISSUE THREAD

**Issue by DeerInHeadlights2** [BeipDev/BeipMU#107]
It would be nice to be able to autoconnect on a network timeout, such as:

Error: The semaphore timeout period has expired.The connection was terminated due to a time-out (ERROR_SEM_TIMEOUT)

**Comment by BeipDev** [comment]
Do you have an easy way to test this once I do add it in?

**Comment by DeerInHeadlights2** [comment]
Sure, just unplug network cable/shutdown wifi and do a command.
