### ISSUE TITLE
Aliases starting with / don't process unless an extra / is added

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#109]
I have some aliases made to essentially simulate commands. /desc, /em, so on, with regex like ^/desc blahblah…
When I try to use them, an error is returned like this:
⛔ Unrecognized Command, use // to send text directly to the muck, or /help for a list of commands

It would be nice if the aliases were parsed before the command validation.

**Comment by BeipDev** [comment]
Figured out a mitigation! We'll add the option 'pass unknown commands through'.
