### ISSUE TITLE
Spawn window horizontal width shrinking upon launch when maximized

### ISSUE THREAD

**Issue by goalcam** [BeipDev/BeipMU#114]
When I close BeipMU while it's maximized, when I start it again, the horizontal width of the configured spawn windows is shrunk. This seems to happen every time that I start BeipMU. Reproduced in Windows 10, using the Windows Store version 4.00.285.

Steps to reproduce:
1. Start BeipMU with it configured to show spawn windows
2. Maximize the window
3. Close BeipMU
4. Open BeipMU
5. Observe the smaller horizontal width of the spawn windows. Closing and starting BeipMU again will result in narrower spawn windows still.

Per Bennet, it may be an issue with how the size of the spawn windows are being stored.

> The issue is that it's using the maximized size to store the width, but then it's being applied to the non maximized size. So it'll shrink each time since it's always thinking it's smaller than it really is.
(or the reverse, I'll find out when I look into it)

Screenshots below

![1](https://user-images.githubusercontent.com/3725404/63630971-b496d300-c5d5-11e9-8ced-f18b621dfeb8.png)
![2](https://user-images.githubusercontent.com/3725404/63630972-b6609680-c5d5-11e9-9455-4170dbc16ff7.png)
![3](https://user-images.githubusercontent.com/3725404/63630973-b791c380-c5d5-11e9-8150-e87827160d60.png)

**Comment by BeipDev** [comment]
Ack, I went to ask you a question and noticed you're gone from the Discord. I was able to fix it by making BeipMU properly save/restore the minimized/maximized window state. Were you manually maximizing each time you start?

**Comment by goalcam** [comment]
Must have been manually maximizing it since it seems to start in windowed mode each time - reflex by now! Which makes me wonder how other people use BeipMU - I get that maximized isn't always desired given modern screen resolutions and the 80 character width standard, but it's certainly a habit to maximize any window (nearly, except for notepad++, calculator, and the like). My bad.

**Comment by BeipDev** [comment]
Ah, just wanted to double check. Now it restores every window exactly as you had it when it was closed.. normal, maximized, minimized, etc.. it'll even remember the non maximized size if you restart then un-maximize. But yeah.. I don't think most people maximize it on a primary screen, though I know of some that maximize it on a secondary display.
