### ISSUE TITLE
Parenthesis and hyperlinks behaving badly

### ISSUE THREAD

**Issue by LimblessLayabout** [BeipDev/BeipMU#115]
![BeipMU_gZZ108CyRT](https://user-images.githubusercontent.com/49801705/63630569-be263800-c5e1-11e9-9b22-84259ac74db5.png)

Current hyperlink behavior ignores or fails to include closing parenthesis, breaking links (especially to wikis) pretty often.
It's been suggested to change the behavior as such; Identify url, proceed until finding a space OR a (. If it finds a ( then look for a ), and repeat until it runs out of ) and THEN find a space after those.

This should leave urls (hidden in parenthesis https://www.example.com) alone, while properly recognizing links with incorporated parenthesis like https://en.wikipedia.org/wiki/!!!_(disambiguation)

**Comment by BeipDev** [comment]
I'm starting with a simpler approach. If it's going to remove  ) from the end of the URL, it looks to see if there's a (. If there's no ( then it removes the ). We'll see if that's a simple enough fix..
