### ISSUE TITLE
Hide Server and/or Character name from puppet spawn

### ISSUE THREAD

**Issue by Precisi** [BeipDev/BeipMU#117]
Hi! I know we talked about this briefly on discord a while back. I figured I'd put it in as a more official request. Would it be hard to make an option for puppet windows to have it so you can toggle for each one whether the spawn window tab displays the server and character name? It would make it so much easier to keep track.

Or, alternatively, just have it where each tab can just be 'named'? 

We had also talked about each server having it's own line for spawns, which would also be cool!

Thanks!

**Comment by BeipDev** [comment]
Right now you have too many tabs so that the names get truncated? And the tooltip on hover isn't convenient to use at a glance?

I forget what the 'each server having its own line for spawns' idea was :| Can you describe it?

**Comment by Precisi** [comment]
Yes, right now I have too many puppet windows because I have three characters across two games. Even shortening to the server and character names to single letters doesn't give enough space on my smaller laptop screen. The tooltip hover isn't convenient because what happens is I will want to say something in a particular chat or etc and have to go hunting for the right one and it's let to me making mistakes I haven't generally made in the past on other clients. It's hardly the end of the world and I can retrain myself to be more patient and check, but it would be nice if I could have better control over the labels on the tab. Ie. "BobRP, BobPages, BobChat, ArxInfo, etc" Just a lot easier at a glance. 

The idea you had mentioned before I believe was that for each character it would be on it's own line of displaying tabs. So character A would be on one line horizontally, character B on a second line, etc.

**Comment by BeipDev** [comment]
Ohh, I don't remember that! I might have been thinking of adding a way to let the taskbar occupy multiple lines (and just fill space like windows does, vs one line per character).

**Comment by BeipDev** [comment]
Current idea is to add a `/tabname <text>` that lets you change the tabs to anything you want.

**Comment by BeipDev** [comment]
I think our new change reversing the order of the names solves this.
