### ISSUE TITLE
Spawns and content-restored / new-content lines

### ISSUE THREAD

**Issue by DeerInHeadlights2** [BeipDev/BeipMU#118]
Spawns could use some indicators to show breaks between new and old content on restore and on reconnect. 2 cases:

1) Restore.  Close a tab, then relaunch the character.  The Output window gets a "Content restored" line but any Spawn windows do not. After you've been active for a little bit it gets confusing if you're seeing old or new content. I keep wanting to respond to channel talk from the day before.

2)  Reconnect Similar situation with just Quitting a character but keeping the tab open, then reconnecting. An Output window actually doesn't get a Beipmu indicator, but generally you get the game's login screen to tell you the divider between old and new output.  But spawns don't get anything in that regard.  You would have to do something to trigger to the spawn yourself on login with a divider. What about giving the Spawn an indicator on reconnect to a character as well?  If you were logged out for a lengthy time you'd want to know where the split in content was.

**Comment by BeipDev** [comment]
For 1. I could easily duplicate the content restored marker across all spawns, is that good?

For 2. It could also put the 'Disconnect' message in all spawns too (do you also want the connected one?)

**Comment by DeerInHeadlights2** [comment]
For 1: Perfect.
For 2: Maybe just the disconnected message would be enough, not sure if having both would add anything.

Thanks!

**Comment by BeipDev** [comment]
For 2 I think the connected would be good otherwise it might look like a spawn is "disconnected" until some activity happens after the disconnected message it might look odd?
