### ISSUE TITLE
Hot-key pic and history toggles

### ISSUE THREAD

**Issue by reflexwolf** [BeipDev/BeipMU#123]
I have found a little hiccup in the new image window, sometimes you don't want to have what has popped up showing to your RL room at large and or its offensive to see (D*ck pics and the like, yes they do happen on some muds) rather than turning off this very neat feature is it possible to add a hot key to toggle it on and off? Something like f12 or the like would work for me to just close it and open it back up, 
Also might be nice to do the same for the history window, I don't know about others but when I mud I tend to just use the keyboard not the mouse. so key strokes are better then having to leave the home row to reach for the mouse.  

thanks much!

**Comment by BeipDev** [comment]
No problem, I added the following two shortcuts you can define to whatever you want:
* History Window - Toggle
* Imaging Window - Toggle

**Comment by reflexwolf** [comment]
thank you so much Bennet! I travel strange places in mud lands :)
