### ISSUE TITLE
Stat Pane Enhancement Thoughts

### ISSUE THREAD

**Issue by Ninjakitten** [BeipDev/BeipMU#126]
I was struck with an idea for playing with the stat panes, and now have suggestions:
1) The ability to change the background colour would be really nice for those of us weirdos who don't use a black screen. It really stands out more than I'd like. If there's already a way, it needs to be made clearer, 'cause I can't find it!
2) The ability to have the name and value in different colours would be nice for some uses.
3) It'd be nice to be able to use \1 etc in the window name (so, if it matched 'NK' as \1, I could have the window come up as 'NK's Whatever' or similar).
4) Putting one-line panes beside each other works reasonably well, but it'd also be nice if there were a way to list stats horizontally instead of vertically in the same pane.
5) As with images, the ability to pop a stat pane into a tabset would be handy in some cases!

**Comment by BeipDev** [comment]
1. There's no current way, but since the background isn't part of any 'stat' trigger itself it wouldn't be automatic. The only way would be by setting it on a stat pane itself.
3. That doen't work already? You should be able to use \n in stat names and values
4. The problem with horizontal is how wide to make them, with vertical it's easy as it's the width of the window, but with horizontal how would it work?
5. Hah, generalized docking with tabs is what you really want...

**Comment by Ninjakitten** [comment]
You skipped one and I'm not totally sure which. I think it was #3, though! 

1) I don't see why setting the background on the stat pane itself isn't a fine solution -- or having 'Stat Panes' in the Options dropdown where we could tell them what background to have just like we do on the Input, Output, and History windows. I'd also suggest having the default colours and font for the stat panes match the output window.
2) I'm not sure how I would use \n in the name or value to have (say) the name in white and the value in green or something. I thought \n was newline; am I wrong? It also doesn't seem to do anything -- If I have a Name of Test\nMoreTest and a Value of \1\n\1 and send A Test Thing, where Thing is \1, I get Test\nMoreTest Thing\nThing, and if I put it in the window name in case this WAS meant for #3, I get \n Test.
3) Request stands!
4) If positioning things horizontally it could by default split the space evenly, but have a space for pixel and/or percentage widths to be specified? Maybe with a tick box for one to take up any unallotted space? This is less of a Thing than some of the others, though, since we can do one to a pane if necessary. I do kind of wish I could have info from multiple lines end up on one line together in a pane (like results of command a/results of command b), but I think I'm really starting to get into a different wishlist there.
5) Yes, but I never claimed otherwise. ;) I'd still like to even be able to have tabs 'behind' the main output window!

**Comment by BeipDev** [comment]
Oops, I skipped #2! I edited my numbering above...

**Comment by BeipDev** [comment]
1. I could put it on the windows themselves, I just worry if you close them you'll lose your background setting as it's not part of the trigger actions.
2. Oh, by \n I meant \1 \2 etc.. the standard regex replacement stuff also, that was meant to be the answer to #3 I fixed it locally after talking to you about the window title.
3. I agree! See #2 
4. Horizontal would require redrawing the whole window on every stat update, plus horizontal scrolling would be needed pretty quickly with not that many stats. I dunno... have you tried mocking it up to see what it might look like?
5. Behind? I'm not sure what you mean?

**Comment by BeipDev** [comment]
Reviewing this one again since it's still active...

1. I can add a right click option to the windows that you could set. It'll be saved as part of the docking layout. Is that good?
2. Separate bug if there's a compelling case?
3. Already done! (couldn't resolve this one since it was a bundle)
4. Difficult :|
5. Generalized docking bug (separate one already logged)

**Comment by Ninjakitten** [comment]
1. Yup!
2. It's not that compelling, it'd just be visually nice at times.
3. Hooray!
4. Alas.
5. Indeed it is.

**Comment by BeipDev** [comment]
1. Done! (marking as locally fixed)
