### ISSUE TITLE
Docked spawn windows don't redraw properly after spawning

### ISSUE THREAD

**Issue by foxbird** [BeipDev/BeipMU#132]
I have a trigger spawn with the following configuration:
```
      Triggers
      {
        {
          Description="OOC Window"
          Example="(OOC) Testing 123"
          OncePerLine=true
          FindString
          {
            MatchText="^\\(ooc\\)|^\\(OOC\\)|^\\(ICC\\)|^\\(icc\\)|^Notify-"
            RegularExpression=true
          }
          Color.WholeLine=true
          Style.WholeLine=true
          Spawn
          {
            Active=true
            Title="OOC"
          }
        }
      }
    }
```
When I connect to the MUD this is for, I get the spawn window which has the text `Connected` in it (I presume Beip is putting that in there) since the MUD immediately sends `Notify- Soandso has connected`. After which, the window doesn't redraw. I can direct more output into it by generating text with the above string prefixes and it is consumed from the main window, however it doesn't show visibly in the spawn. A scroll bar will appear after some amount of input but it doesn't cause the window to draw. To make the spawn redraw I must expand the window to be taller. Shrinking it doesn't force the redraw.

Smooth scrolling has no effect on the functionality. The window is docked at the top, and 'restore previous text' is disabled so the window always starts empty when first launched.

**Comment by BeipDev** [comment]
I tried a test of creating this same trigger and a char with a connect string that sent text to that spawn but it appeared. Do you have anything non default in the spawn window settings? Like scroll to bottom or something?

**Comment by BeipDev** [comment]
Oh yeah, this was fixed in the beta. Marking as fixed
