### ISSUE TITLE
Option to not remove trigger spawn text from the main window

### ISSUE THREAD

**Issue by foxbird** [BeipDev/BeipMU#134]
When creating a trigger that directs text to a spawn, the text is always delivered only to the spawn window and not also put in the main window. This works great if you want to keep everything totally separate. However, in a MUD you generally look at the main window area most of the time and only need the spawn window to capture chat stuff you might have missed while being spammed with battle text. So, for me, I'd prefer to read everything 'in place' with context if I can (leaving the spawn text in the main window), and have the spawn window for reference (IE: `copy` the text to the spawn instead of `moving` it to the spawn). I suspect this should be an option in the trigger spawn settings to `Copy text` or something of that nature.

**Comment by BeipDev** [comment]
Added checkbox 'Copy line instead of move (Original line is still in main output)' in the spawn trigger tab that does what you want.
