### ISSUE TITLE
Smart paste from file doesn't handle line endings correctly

### ISSUE THREAD

**Issue by mystfox** [BeipDev/BeipMU#136]
When trying to send a text file with smart paste, every line ending (plain `LF` or `CR LF`) gets transformed into `LF CR LF`. At least the muck I'm using this on is interpreting the extra `LF` as a whole extra line, ignoring that there is no `CR`. This is not completely horrible for editing a MUF program, as it will only make it look horrible when listed (and break doc commands for `@view`), but makes it pretty much impossible to use this, say, with `lsedit` to set whole prop lists. You can see this here: ![Network Debugger output showing this](https://i.imgur.com/Wlu3a5k.png)

**Comment by BeipDev** [comment]
Ah, I see the bug. It was indeed adding an extra LF character in smart paste. It'll be fixed in the next build. Thank you for the great debug info!
