### ISSUE TITLE
Enhancement: "Don't capture until" or similar

### ISSUE THREAD

**Issue by Ninjakitten** [BeipDev/BeipMU#137]
Just realised this was never put here. This is the idea of essentially being able to do the opposite of capture-until -- *not* spawning anything between the first match and the end match. This can be used to prevent things like OOC comments in bboard posts spawning as actual OOC remarks instead of being kept with the rest of the post in the main window.

**Comment by Ninjakitten** [comment]
Just a note to say I still wish for this ability regularly. Twice already today.

We had talked about it essentially being a capture-until with the direction of the main window rather than a spawn.

**Comment by BeipDev** [comment]
Did you have any more ideas on how to expose it in the UI?

**Comment by Ninjakitten** [comment]
![nospawn](https://user-images.githubusercontent.com/5254533/75792375-bda1f300-5d22-11ea-89e3-2da9dcfd3c78.jpg)
