### ISSUE TITLE
Enhancement: Animated gif support in image window

### ISSUE THREAD

**Issue by BeipDev** [BeipDev/BeipMU#138]
Title says it all, upvote (thumbs up react) this if you want it.. If enough people want it, it'll happen!

Edit: Note that this won't work for gif links that are actually web pages (like giphy links) or gifv (which are really movie files).

**Comment by Seraphiel0** [comment]
As long as there's also an option to disable it.

**Comment by Ninjakitten** [comment]
My request is, if this happens, that we can please have it only run the gif when the image is hovered over, like Discord allows.

(Being able to disable the option entirely would also work, I guess, but I *would* like to be able to see the gifs without loading them into a browser... when and *only* when I decide I want to see it moving.)
