### ISSUE TITLE
Enh req: /logtop (similar to /logall, but "from top of window" behavior instead)

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#150]
Currently, using this function requires selecting from a menu, then browsing to a file (from a location which isn't saved per world, so usually involves lots of superfluous clicking).  Would be nice to have a command line variant for easy macroifying.

**Comment by BeipDev** [comment]
Sounds good, so what syntax would you prefer?

**Comment by BeipDev** [comment]
(maybe even change /log to have parameters and more options so it's all one big command vs many?)

**Comment by Seraphiel0** [comment]
the same syntax should be fine. /logtop <path\file>.  I don't have a pref on whether it's /logtop (like /logall) or /log /top.
Some people may have macros or things already set up using the existing syntax, so a /logtop command might be the least disruptive to current users.

**Comment by BeipDev** [comment]
/logtop it is, and it's already in the beta!
