### ISSUE TITLE
Puppet windows not closing

### ISSUE THREAD

**Issue by Lestandish** [BeipDev/BeipMU#151]
I grew up on SimpleMu. I used to do spawn windows constantly, and I have done the same with the puppet idea.

But, those windows do not close when I close the program, even if they are no longer connected. They are waiting, open, and will not go away unless manually done. Also, if those puppet windows are not closed manually, the parent instance stops recognizing the puppet code.

Either having the connect back to the prior puppet/spawn window, or even just a simple button to close all windows, or all windows but current, would be nice.

**Comment by BeipDev** [comment]
Ah, if you want the puppets to reconnect with the parent automatically, just check 'Connect when player connects'. Then if you reconnect in the player, the associated puppet will also reconnect.

If you don't want that, a disconnected puppet window can reconnect at any time (one simple way is to just try to send something in that disconnected puppet window).

Does that solve the issue?

**Comment by BeipDev** [comment]
Oh, I should mention.. 'Connect when player connects' is in the Puppet dialog in the connect dialog.

**Comment by Lestandish** [comment]
Well, I just tried that. I had ignored that option before because I had tried to use auto-connect, so what came in and set it off would pop a window when it was needed, instead of having every one open, used or unused. When I tried your solution, I immediately had every possible window, used or unused, pop up on connect. 

Now they are there, like it or not, used or not and they still don't close.

At this point, it may be more feature than bug. If I do this, I will no longer have to worry about the reconnect disabling them. This makes auto connect moot. I'd rather use autoconnect, this means I have less to close by hand manually.

Great program otherwise, I recommend it to others, but this makes in my humble opinion auto connect moot. At least I know how to make auto connect useful again. Just shut every window manually whenever I use it.

**Comment by BeipDev** [comment]
Yeah, the options for the puppet windows were added many years before it would remember your window settings on restart, so they do seem a bit silly together.

It'd be easy to add an option to not remember the tabs opened on close if you'd like, or even a command like '/closedisconnected' to close all disconnected tabs. Up to you!

**Comment by Lestandish** [comment]
I would love either, both would solve the problem. Can you aid me how to do this?

**Comment by Lestandish** [comment]
The option would prevent people from having to ask what the command is every so often, right?

**Comment by BeipDev** [comment]
Yeah, plus it's a familiar feature with browsers to not remember the tabs on close.

So I'll add "Remember tabs on exit" in the preferences. I can add that for the next release coming soon... sound good?

**Comment by BeipDev** [comment]
@Lestandish Ping!

**Comment by BeipDev** [comment]
Closing due to lack of response, plus it's fixed with remembering all of the windows as mentioned above.
