### ISSUE TITLE
Gagged lines say "line was gagged in log file" when gagged

### ISSUE THREAD

**Issue by Entity447B** [BeipDev/BeipMU#152]
I've got a trigger that squelches some messages. Ideally I'd like them to be rendered totally invisible. However, each time they're received the message "line was gagged in log file" appears in the output window.

I have "Gag this line" and nothing else checked in the trigger's Filter tab.

**Comment by BeipDev** [comment]
Fasincating, looks like I removed the 'Show gag message' from the UI (it defaults to off) but you must have had an old config with it set at some point.

I removed the message from the code entirely now (as trigger debugging is superior), and it'll be in the next release.

If you want to fix it immediately in your version you'll have to edit your config.txt manually to remove the 'Message=true' line inside your Gag triggers.
