### ISSUE TITLE
Hash function is available for text background, but not paragraph background

### ISSUE THREAD

**Issue by Katherine1** [BeipDev/BeipMU#159]
When making triggers, the background color for the text can be selected by a hash function. However, over in the paragraph tab, the paragraph background color does not share this functionality. It would be great if the paragraph background color could also be set via hash function.

**Comment by BeipDev** [comment]
I have the UI working then I realized.. what text do you want it to use to generate the hash colors? The entire line or one of the regex subexpressions?

**Comment by Katherine1** [comment]
I heard that the existing Hash options in the appearance tab use the first regex subexpression. That would be the best for me on the paragraph styling as well.

**Comment by BeipDev** [comment]
The fixes are in the currently posted beta, let me know if it works!

**Comment by BeipDev** [comment]
Fixed in the latest release, publishing in progress!
