### ISSUE TITLE
Clear "important activity" red box when tab selected

### ISSUE THREAD

**Issue by DeerInHeadlights2** [BeipDev/BeipMU#162]
Minor thing.  

If you have the normal activity indicator set (i.e. Options-> Preferred -> Activity Notifier  set to "Blink") then when activity happens, the tab colors and starts blinking. When you select that tab the coloring/blinking immediately goes away.

But if you have a trigger fire with a tick in Activity-> Show as important activity on windows tab (the red box)... when the trigger fires you get the red box on the tab. But selecting the tab, the red box remains until you click away, either to another Beipmu tab or to some other window (Chrome, etc).

Any way to make the triggered red box go away as soon as you make the tab active, like the other activity notifier does?

**Comment by BeipDev** [comment]
Just annotating this before closing it, as we discussed this when it was first posted (wow, a few years ago!)

The main issue was that if you get important activity, then click the taskbar to switch to the app you'd never see it as it'd be cleared the moment you activated the window.

It's why it only clears it when clicking away from the window (as you've already seen it, clearing has no harm and sets it up for the next time).
