### ISSUE TITLE
Pueblo lost on lost link and reconnect

### ISSUE THREAD

**Issue by DeerInHeadlights2** [BeipDev/BeipMU#165]
Connected with Pueblo on.  Internet goes down, connection lost. Reconnect. Pueblo frequently stops working until disconnect and reconnect again. 

Using "/reconnect all" caused all disconnected windows to reconnect without Pueblo coming back.  While connected then, right click on tab to Disconnect and then again to Reconnect, restored Pueblo.

Not sure if it is /reconnect that is not launching Pueblo again as opposed to the menu somehow.  Or if is something about the ungraceful disconnect not restoring it on a reconnect, but Beip doing the disconnect then reconnecting it handles it properly.

**Comment by BeipDev** [comment]
Hmm, I wonder if something is happening on the server side. I debugged it locally and any disconnect will reset the 'using pueblo' flag to false. Reconnect is just a connect if disconnected.

The way the Pueblo gets enabled is if you have the option set, and the server sends "This world is Pueblo x.xx" AND the server then sends "</xch_mudtext>" to enable Pueblo mode. I wonder if the server is in a different state, where if it boots your previous connection it doesn't send you one of those. Can you look at the network debug output to see what happens on connect?

**Comment by BeipDev** [comment]
I discovered yesterday that the 'try to reconnect on disconnect' takes a shortcut and doesn't call Disconnect() internally. So it's my bug after all! Looks like the shortcut wasn't good.

I'm reworking the code to simplify it. Lots of really old assumptions and designs still in there.

**Comment by BeipDev** [comment]
Fixed in 316
