### ISSUE TITLE
Add alias buttons bar

### ISSUE THREAD

**Issue by foxmajik** [BeipDev/BeipMU#167]
Coming from Trebuchet I miss the button bar at the top where the user could easily add clickable buttons that would execute a script or a list of commands as if they had been entered into the input window. I read through the documentation for this client and wasn't able to find any similar functionality, so I'm suggesting it as a feature request.

**Comment by BeipDev** [comment]
@foxmajik We came up with something that might suit your needs! Are you still interested?

**Comment by BeipDev** [comment]
Fixed through WebViews in latest version
