### ISSUE TITLE
There are no installation instructions

### ISSUE THREAD

**Issue by philgoetz** [BeipDev/BeipMU#168]
The docs merely say, "There are two ways to install BeipMU, either the Microsoft Store( https://www.microsoft.com/store/apps/9NBLGGH4TRSV ), or to manually unzip one of the releases posted here."

But the zip for version 309 contains no executables, so there's no way to run the program after unzipping it.
If I'm supposed to compile it, I need a LOT more instructions than that.

**Comment by philgoetz** [comment]
Okay, the issue is that, instead of clicking on the link that looks to me like the one you're supposed to click on--the tag that says "v309" and "Latest", under "Releases", I needed to click instead on the "beipdev.github.io/beipmu/" to the right of an icon for "link", which I didn't click on because it doesn't say it's a link to the release, and sounds to me like a link to the project home page. Probably this is default github behavior and can't be changed.

**Comment by BeipDev** [comment]
Yeah, on the release you should see the 'Assets' list and the BeipMU_309_x64.zip (or x86 one). I guess I never thought about it as I'm used to github downloads. I never thought to click on the v309 tag.

And yep, that's just how github behaves (and also why the store link exists, it's all automatic). Glad you figured it out!
