### ISSUE TITLE
Mute button for tabs!

### ISSUE THREAD

**Issue by Tokeli** [BeipDev/BeipMU#169]
I make extensive use of puppets for filtering out pages on every MU* and character, to their own tab. This is generally fine but it can very, very frequently be annoying when the parent tab is in a public room and I get constant taskbar notifications, when I only want to keep track of a few conversations in the child tab.

It would be super nice if tabs were able to get a right-click option on them to simply mute/unmute them, temporarily turning off all activity notifications for that tab- like say, sounds and everything in an activity trigger. And Windows taskbar flashing. A simple setting that's per-tab and not saved anywhere!

**Comment by BeipDev** [comment]
Should be easy enough to do. I think just 'mute' might be misleading as I'd think it'd just disable sound notifications. The hard part will be what to call it.

How about 'Blink taskbar icon on activity' as a by default checked item? Just saying 'Taskbar' makes it seem like it could be the taskbar inside the BeipMU main window. Or do you have any better suggestions on the name?

**Comment by BeipDev** [comment]
Almost forgot, this was added in the last release! There is now a 'Show activity on taskbar' right click option per tab.
