### ISSUE TITLE
Shift+double click to select paragraph

### ISSUE THREAD

**Issue by DeerInHeadlights2** [BeipDev/BeipMU#170]
Enhancement request.  
 
Submitting for a blind friend.

Apparently in MushClient if you shift + double click, it will select the entire paragraph.  Which they said was very helpful.  I tried shift/alt/control + double click in BeipMU and all of them are same as double click and just get the single word.  Would it be possible to copy the whole paragraph as an enhancement? 

Thanks!

**Comment by BeipDev** [comment]
It is done.

**Comment by BeipDev** [comment]
Fixed in build 322
