### ISSUE TITLE
Tool tips can get very persistent under Wine.

### ISSUE THREAD

**Issue by ACleverDisguise** [BeipDev/BeipMU#171]
![image](https://github.com/BeipDev/BeipMU/assets/40811206/4208f477-3643-4d4b-9689-0abc9e7cc62d)
Those tool tips are from BeipMU running on a Linux Mint system.  On a completely different desktop.  They cannot be gotten rid of.  They sit on top of every other window anywhere on the system.  The only way to kill them is to shut BeipMU down and restart it.

I realize that Linux is not your target so I don't expect the bug to be solved: this is a Wine interaction issue, not a Windows one.  What I would like to see, though, is an option to turn off tool tips.

**Comment by BeipDev** [comment]
That is a horrible problem. Good news! I actually fixed this in the last update a few weeks ago. I test things on Wine when people complain. So the future is now, let me know if it works properly for you too:

From the 322 changes:
"Reworked tooltips to not use TrackMouseEvent, so should work better on Wine"

**Comment by ACleverDisguise** [comment]
Sorry for the delay in response.

Yes, the latest version eliminates the problem.  Thanks for anticipating the bug report before I even made it!  :D
