### ISSUE TITLE
UI Fix: Settings - Scripting - Startup script location is unclear

### ISSUE THREAD

**Issue by diamondmx** [BeipDev/BeipMU#176]
Allow the user to see what folder the application is looking for the startup script in, either by allowing them to browse there to select the script, or by showing a path so they can navigate there themselves.
Ideally, also indicate to the user if the script listed is found, too. (So they know if they've messed up the script path or name)

**Comment by BeipDev** [comment]
Interesting, I don't know if it even has a default path currently (scripting is hardly used by anyone, so it's rather neglected). It might be tricky if it's the store version and it's using the hidden folder. (it's %appdata%\BeipMU but it's in a virtualized folder so the app doesn't know the actual path sometimes).

That UI was added back when people would just put the .exe somewhere and their scripts next to the .exe. Would be easy to at least show that the file exists or not.

**Comment by BeipDev** [comment]
I have a 'Choose...' button to the right of the script path now to make it easier to pick a filename.
