### ISSUE TITLE
MCP Package: dns-com-vmoo-client

### ISSUE THREAD

**Issue by lisdude** [BeipDev/BeipMU#18]
This is a pretty simple one that identifies the client to the server and allows the client to inform the server of the width of the window. The 'specification' is below:

```
6.2 dns-nl-vgmoo-client [1.0-1.0]

    The following messages are defined:

        dns-nl-vgmoo-client-info(name, text-version, internal-version, reg-id, flags [,x-vmoo-flags]) (Client to Moo)
        dns-nl-vgmoo-client-screensize(cols, rows) (Client to Moo)

    dns-nl-vgmoo-client-info(name, text-version, internal-version, reg-id, flags, ...)

        is a message which uniquely specifies which version of a client is used. Whit this information it is possible to check for specific versions of clients to prevent bugs from occuring and to provide online assistance to users of specific clients.

        The following 'flags' are defined: p (a proxy is used to connect to *THIS* world), l (vmoo links).
        The following 'x-vmoo-flags' are defined: m (multimedia), w (popup windows)
        (Other clients are encouraged to support similar information)

        Name followed by Text version should form the complete client name

        internal version is an integer which defines the version of the client in an easy parsable way. (To enable client-bug workarounds in moo). (toint() is used to parse this string) (0 if not supported)

        reg-id is a numeric token which provides a unique user number to the moo. (In VMoo this number is some part of the registration number).

    dns-nl-vgmoo-client-screensize(cols, rows)

        Sent by the client whenever the screensize of the main text window changes.

        (Please, only send this message after connecting en when the screensize changes and not when for example the screensize is increased by less than 1 character.).
```

Real world examples of the messages sent:

```
C->S: #$#dns-com-vmoo-client-screensize B283A523 Cols: 231 Rows: 52
C->S: #$#dns-com-vmoo-client-info B283A523 Name: VMoo text-version: "Pro 1.6b" internal-version: 920 reg-id: 983568023 flags: l x-vmoo-flags: mwa
```

Having said that, I do have a slight modification to ask for. Could you make the client resizing optional? I don't like how it unidles me when I resize a window, which happens every time my monitors wake up. Ideally, there would be two ways to invoke this: 1. Automatically when the window resizes, if the option is enabled. 2. Manually from the menu or, ideally, via keyboard shortcut. Or even /screensize would work.

**Comment by BeipDev** [comment]
I started adding the dns-com-vmoo package. Right now it only sends the client ID, not the sizing stuff (since the sizing stuff is fuzzy given the window isn't really a fixed width in chars due to proportional fonts).

By 'unidles you when you resize' are you referring to how vmoo and this package work together?

**Comment by lisdude** [comment]
Yeah. With VMoo it's not optional to send the window size on resize. And MOO servers consider any network activity to mean the player is unidle, even if it's out of band.
