### ISSUE TITLE
Bug: HTML gets erroneously parsed in triggers with regex

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [BeipDev/BeipMU#180]
In a trigger with Filter Text and Parse HTML checked, HTML _in the regex replacements_ is also parsed as HTML. Example:

Matcharoo:
```
^(.+) pages, "(.*)" to (.+)\.$
```

Replacement:
```
<font color="#ffffcd">\1</font> <font color="#cdcd00">pages, "</font>\2<font color="#cdcd00">" to</font> <font color="#ffffcd">\3</font><font color="#cdcd00">.</font>
```

When receiving `Nina pages, "That sounds Fun<tm>" to Devi.`, the angle brackets (or indeed anything with angle brackets) are erroneously treated as HTML tags, and dropped because `<tm>` isn't a valid tag. In this example, if someone paged you with `"You color text <font color="#ff0000">like so</font>"`, presumably it would actually color the text.

**Comment by BeipDev** [comment]
Fixed in build 327
