### ISSUE TITLE
Enhancement: Tabs in notes/"Character info" window

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#181]
Right now the character info panel is just one bighuge text file.

Would be nice to have something like modern Notepad where it has some tabs across the top to sort out this info into different sections.

**Comment by BeipDev** [comment]
Ah, we have a solution to that! Use WebViews! Then you can use an online document system much fancier than notepad, and dock the window.

If that doesn't help, can think if there are other easy ways to make it better. Right now it's just a window showing the 'info' field. It wasn't meant to scale too far.

**Comment by Seraphiel0** [comment]
Got it working with 

/webview url="https://onedrive.live.com/redir?resid=<notebookGUID>"

but had to use

/webview url="edge://flags"

to enable dark mode
