### ISSUE TITLE
UTF8 code hijinks, or something else?

### ISSUE THREAD

**Issue by betweenthefog** [BeipDev/BeipMU#2]
Since updating Beip to build 263 or so, I've been getting wacky Invalid UTF8 code errors all over the place, both in text MU-side, and text I send to the MU*. For example, I was copying and pasting a part from an article.

Here's what I copied into my input window:

Lyons, the UCLA physicist, said Steve “appears not to formally be aurora.” It’s far closer, he said, to a phenomenon called airglow, in which the upper atmosphere releases a faint amount of light as it is heated by the sun and the planet’s surface. “You can see [airglow] all over, but it’s not something you can notice with your eye, and it’s not narrow,” like Steve, he said.

Here's what it became:

Lyons, the UCLA physicist, said Steve (Invalid UTF8 code)�pears not to formally be aurora.(Invalid UTF8 code)�t(Invalid UTF8 code)�far closer, he said, to a phenomenon called airglow, in which the upper atmosphere releases a faint amount of light as it is heated by the sun and the planet(Invalid UTF8 code)�surface. (Invalid UTF8 code)�u can see airglow all over, but it(Invalid UTF8 code)�not something you can notice with your eye, and it(Invalid UTF8 code)�not narrow,(Invalid UTF8 code)�ike Steve, he said.

Just about everything's kind of wonky, and I'm not sure if it's something on my end, or that the MU*s I hang out on don't handle UTF8 format, or if it's Beip itself.

EDIT: A friend of mine suggested a bit of info that could be useful for debugging purposes. Here's the @version of the MU*s I got errors on:

Last restarted: Sat Jan 27 12:06:48 2018
PennMUSH version 1.8.6 patchlevel 2 [12/19/2017]
Git revision: c8f50b3
Build date: Sat Jan 27 12:03:55 EST 2018
Compiler: gcc
Compilation flags: -g -g -O2 -W -fstack-protector -Wa,--noexecstack -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char   -I/usr/include -I/usr/include/mysql

&

ProtoMUCK 2.1-r38 (Muck2.2fb6.91) on GNU/Linux: Linux debian 4.5.0-x86_64-linode65 #2 SMP Mon Mar 14 18:01:58 EDT 2016 x86_64 GNU/Linux
Compile-time Options: DescrFile Color Detach Compression ProcessAPI MemBased Userflags MUF:Sockets MUF:UDP MUF:Edit MUF:PCRE Debug:0

**Comment by BeipDev** [comment]
Ah, sounds like the UTF8 text encoding default isn't what you want on this MU*. Just open up the server settings and change the 'Text Encoding' from 'UTF8 - Unicode' to 'CP-1252 Windows'. Does that fix it?

**Comment by betweenthefog** [comment]
Sure does! Forgot that was even an option there- kept just looking at the character settings tab.
