### ISSUE TITLE
Beip losing logging and sound functionality after it is open for extended periods

### ISSUE THREAD

**Issue by nimriye** [BeipDev/BeipMU#22]
Sadly I cannot pinpoint any particular kind of behavior or act that leads to this, other than me leaving the Beip program open and connected for extended periods of time (in this instance, it was open and connected for about six days).

What happens is that the triggers I have setup to play a .wav sound file on activity, will stop firing and no sounds will play. At the same time, I lose the ability to click 'Start Logging' or 'Starting from Beginning' in order to log my window output. The dialog box to ask where to save the log file won't pop up.

I began to observe this issue beginning with 3.00.265.

**Comment by BeipDev** [comment]
Interesting, with build 265 I changed the sound playback to use the new Windows 8+ media code to playback more than just .wav. I assume you're using Windows 10 (given nobody uses Windows 8, hah).

Bringing up the explorer file picker dialog is "expensive" (compared to other things BeipMU does) so there might be a resource problem. Can you look at the memory usage in task manager for BeipMU.exe?

Also, do you use a lot of sounds? From what you describe it sounds like it's related to lots of sound playback over time.

**Comment by nimriye** [comment]
Thanks for your reply! I am using Win 10 yes! I should have mentioned that.

It does sound like it might be a resource issue over time. Yesterday when I noticed this happening, I checked and I had had the program open for almost 6 days. That entire time it has been playing sounds. I do have a lot of sound events... I have a trigger that plays a sound whenever new activity is received in a window that does not currently have focus. With some spammy windows, this can result in a sound every few minutes, as I click away and back again.

I restarted the program last night, and as of this afternoon it's reporting about 15 mb of memory usage in Task Manager. My friend who has had Beip version 257 open for a week+ on her Win10 machine, reports about 2.5 mb of memory usage in contrast.

As a test, I may restart it again, leave it open, and see how crazy it starts to look in Task Manager over time, and then test it again with the sound triggers turned off.

**Comment by BeipDev** [comment]
I did a test that would keep playing a sound 10 times a second and I noticed that the BeipMU.exe process does start to use more and more OS handles. I tried to debug it for a while to figure it out and it appears it's stuff inside of the windows media code. Even if I completely delete every object I have on my side the leaks remain. Luckily the rest of the code doesn't allocate handles like this, so only OS things have a problem.

But I do see it! Unfortunately I'm not sure what to do. I did make a local change to have '/silence' shut down everything audio related instead of just stopping playback. This might restore enough handles to let you save a log, but it won't solve the problem.

**Comment by nimriye** [comment]
After some testing I do also notice the Beip v269 process ramping up to 130+ MB of memory usage over the course of a day, from a starting point of about 3 or 4 MB, via sound triggers and the opening of 'start logging' dialogs.

I reverted back to using Beip v257, and haven't observed the same leak, even with with sound triggers in place. I opened the program yesterday and as of tonight, the program is only at 9.6 MB of memory usage (from a start of 3-4 MB), and the increases in usage were due to me starting logs in three windows over the course of that time. (Incidentally reverting back to v257 also fixed another issue I was having with v269, where my input font Monaco was overlapping itself in an unreadable way).

It seems something did change between those two versions. Windows 10 did release a new update in that time that was significant enough it altered some OS settings (which I had to change back); perhaps something in that update changed how Windows playback interacts with Beip. too.

Regardless, thanks for your time and your replies here!

**Comment by BeipDev** [comment]
In build v265 I did change the sound code over to a different API that allows for more than wav plus multiple sounds at once. Previously I was using an ancient playback API that was limited to one wav at a time. I can make an option to stick with the old API if it was working fine for you.

For the input font, I also switched to using RichEdit 4.1 in build v259 to get nice squiggly lines on misspelled words. It's the input window that the Monaco font renders badly with? If possible, can you attach a screenshot of it here?

And thank you for the reports! I'd never have known about that sound resource link without your post.

**Comment by nimriye** [comment]
I'm glad if the reports help! Beip has been my staple client for many years.

The old API does seem to be working okay, and I think the new one doesn't like my system in various ways beyond the above issue (playback is unusually loud and sometimes it seems to play the sound more than once even if I only have one in the trigger), so an option to toggle to the old  API would be great!

As for the input font, it is in fact only in the input window where it renders strangely. It starts with v259 (v257 was okay), and most fonts I tested seemed to be fine except for Monaco, which is a 'taller' font than usual. Here is a screen of what it does.

Thanks again.

![beipbug](https://user-images.githubusercontent.com/40511921/41852940-80008646-785a-11e8-94ce-510d52118759.JPG)

**Comment by BeipDev** [comment]
An update, I reported the media memory leak to Microsoft and they confirmed it and there will be a fix coming in a near future update. As for the volume levels, the old sound API I was using could only ever play one sound at a time so the volume issues might be the same trigger hitting multiple times in a line. Is that possible with your triggers? I can still put in a way to revert to the old sound code if you still want that.

For the input window I noticed there are some other weird bugs with fonts, like certain fonts don't get set properly. I switched to a new version of the system RichEdit control (to get the squiggly underlines) but it might be more trouble than it's worth.

**Comment by nimriye** [comment]
Thanks for the update! Hopefully Microsoft patches a fix.

As for the sounds, it might be possible. It's a regexp trigger set to `.*`, 'only when away' and 'once.' Theoretically it's just supposed to match on any kind of new activity in an inactive window.

I'm not exactly sure where I got that `.*` was what to put in to match for 'anything.' It was quite a long time ago. Maybe that pattern matches multiple times in a single line and it's spamming itself. An option to revert would be great, if there is not a way I can try to fix on my end.

And it might well be the RichEdit, for the fonts. I hadn't tried many other fonts but there are some oddities with the one I use in the input window.

**Comment by BeipDev** [comment]
The Microsoft patch is live! (at least it's live in build 17763.1 for me). It took them a while to stage the release, but it looks like it's finally becoming publicly visible. My test program shows constant memory usage now, where before this update it was ever increasing.

I'll resolve this bug now that it's fixed.
