### ISSUE TITLE
Folders for Triggers & Aliases

### ISSUE THREAD

**Issue by bash550** [BeipDev/BeipMU#3]
Hi. Great client. I and some others use a huge amount of triggers and aliases. Would you consider adding an option to group triggers and aliases? For example I could have a Group called LOCATIONS: and then assign sub-triggers that all deal with locations around a MOO.
The same could be done with aliases to keep everything neat and easily organized.

**Comment by BeipDev** [comment]
Interesting! On question, the triggers are processed in the order they are listed. Do you expect folders to work the same way, where they'd run as 'always hitting' nested triggers at the location that the folder is?

**Comment by bash550** [comment]
I would think so. Grouping them would just be a way to keep them organized and to take up less space. I would like to be able to skip to a particular trigger among hundreds at a glance. I'd also assume that all the triggers in the folder would hit, irrespective of the others. Though if possible, you could add the sub *if-then* function within the folders themselves.
