### ISSUE TITLE
Universal Speech Screenreader API

### ISSUE THREAD

**Issue by bash550** [BeipDev/BeipMU#30]
Would it be possible to implement [this](https://github.com/qtnc/UniversalSpeech) in the future? Some blind players could benefit from it in BeipMU.

**Comment by BeipDev** [comment]
Definitely! But I'll need someone to help me figure out exactly how it should work design wise.

**Comment by bash550** [comment]
Not at the moment, but I could check with the staff at Miriani.

**Comment by distantorigin** [comment]
Miriani host here. (I was browsing and couldn't help but notice the specific mention!)

I can be reached on Discord @distantorigin#0871 if you'd like to discuss an implementation. Or here, if you'd prefer. I've used BeipMU in the past and would love to help in whatever way is possible.

**Comment by BeipDev** [comment]
We experimented a little but then didn't come up with a final plan. Back to needing users who need this in order to progress.

**Comment by BeipDev** [comment]
I added support for screen readers through IAccessible support in the output window in build 300
