### ISSUE TITLE
Specific parts of config export.

### ISSUE THREAD

**Issue by bash550** [BeipDev/BeipMU#31]
Another request :) 

Could you please implement a way to export configs so someone else can use them? Specific parts of the config too, if possible. So a person could give the worlds and only the colour triggers in their config to a friend, for example.

Thanks!

**Comment by bash550** [comment]
Doesn't have to be specifically colour triggers. Just the ability to specify what I would want to send in the custom config to have someone set up their client quickly.

**Comment by BeipDev** [comment]
The latest beta lets you export/import triggers, how's that?
