### ISSUE TITLE
Focus on spawn windows.

### ISSUE THREAD

**Issue by bash550** [BeipDev/BeipMU#34]
Would it be possible to be able to have focus on on any of the spawn windows in future builds? 

In other words, a mouse click would allow you to pause any spawn window you focus on.

**Comment by BeipDev** [comment]
I originally had it where you could set the focus to a spawn window, but quickly hated it as it made it so that you couldn't type into the input window without clicking exactly in the input window.

You basically want a pause button per spawn window?

**Comment by bash550** [comment]
Yeah, a pause button per spawn window would be helpful.

**Comment by BeipDev** [comment]
Would a right click option be ok?

**Comment by bash550** [comment]
Sure, that would work.
