### ISSUE TITLE
Crash when closing tabs with right-click menu

### ISSUE THREAD

**Issue by kithylin** [BeipDev/BeipMU#36]
BeipMu Crashes at random when right-clicking on a random tab/button and then left-clicking on "Close" to close it. Only happens when logged in to two or more characters/mucks at the same time.

OS: Windows 7 x64

Re-Produce: Login to 2 or more buttons at the same time, right click on any window/button/tab to the left of the currently selected tab/button, on the "tab bar" at the bottom and then left-click on "Close". Does not always reproduce exactly every time. Completely random when it does occur.  Sometimes can go days of using Beip and not seeing it. Then suddenly when least expecting it, try to close a tab/button and it crashes.

**Comment by BeipDev** [comment]
You mentioned closing this as there's been no repro since you logged it. If it happens again we can reactivate.

**Comment by BeipDev** [comment]
Since there's no action we can take right now let's close it and hope for a callstack when it happens again.
