### ISSUE TITLE
Provide modern JavaScript via the jsRT/Chakra

### ISSUE THREAD

**Issue by jj4th** [BeipDev/BeipMU#39]
Would it be possible to provide a modern javascript scripting target, perhaps by leveraging the jsRT/Chakra?

https://blogs.windows.com/msedgedev/2015/05/18/using-chakra-for-scripting-applications-across-windows-10/
or
https://docs.microsoft.com/en-us/microsoft-edge/hosting/chakra-hosting/targeting-edge-vs-legacy-engines-in-jsrt-apis

I'd personally love it if we could use v8 as a scripthost but I suspect that would prevent it from being approved for the Windows Store.

**Comment by BeipDev** [comment]
Locally fixed, will be in the next build!
