### ISSUE TITLE
Requesting fast text flashing in trigger options.

### ISSUE THREAD

**Issue by bash550** [BeipDev/BeipMU#4]
Would be neat if we could have this option to alternate flashing speeds to emulate flickering neon lights or a flashing light on an item. Or whatever.

**Comment by BeipDev** [comment]
To clarify the option, it will be a sub-option that's titled "Use fast flash" that only has an effect if you check "Flashing" in the appearance tab?

**Comment by bash550** [comment]
Yeah, that would work perfectly.

**Comment by BeipDev** [comment]
Ok, it'll be in build 269, close this when you're happy!

**Comment by bash550** [comment]
Thanks Looking forward to the next build!
