### ISSUE TITLE
Keybind for 'convert carriage return to %R'

### ISSUE THREAD

**Issue by nimriye** [BeipDev/BeipMU#44]
As mentioned in another ticket, it would be nice to add the ability to assign keybinds for 'Input Text Conversion - Convert Returns to %R' and 'Convert Tabs to %t.' I currently use a workaround to bind them to F1 and Shift-F1.

**Comment by BeipDev** [comment]
Done! It'll be in the next build.

**Comment by nimriye** [comment]
Thank you!!
