### ISSUE TITLE
Request: Add Delta time to line tooltip

### ISSUE THREAD

**Issue by Avrii** [BeipDev/BeipMU#58]
An optional enhancement to the popup tooltip which shows an Output Window line's timestamp, as spoken about in Discord!

**Comment by BeipDev** [comment]
What time units would you like in the '47 minutes ago' string? Do you want it to just be the most significant time unit? Like '5 days' '8 hours' '34 minutes'? Or the whole time? '5 hours 34 minutes 10 seconds ago'?

**Comment by BeipDev** [comment]
![image](https://user-images.githubusercontent.com/30326317/51797323-f5e91080-21b5-11e9-822c-4c0bc9e04eab.png)

**Comment by Avrii** [comment]
Two most significant seems reasonable. At any rate, looks excellent! 👍
