### ISSUE TITLE
Request: Text to speech options in triggers

### ISSUE THREAD

**Issue by JinxLuckless** [BeipDev/BeipMU#60]
I would love some text to speech options in triggers. 

I was wanting to use it the way Cuprohastes on the Discord was suggesting, where you can set a trigger to read off text aloud, saying, 'You have a new page.' Or any other text that you enter in there.

Basically, an option called 'Speak this' or something, as you suggested. Also as mentioned, you could set it to 'speak everything' to get text to speech of everything coming in, or everything that matches your trigger, etc.

**Comment by BeipDev** [comment]
And done! I did it where you can speak the line or even use a regex replacement style string. Should cover everything. Enjoy!
