### ISSUE TITLE
Feature Request: Two Input Windows

### ISSUE THREAD

**Issue by skewskewskew** [BeipDev/BeipMU#61]
Please add an option to enable a second input window, right below/above the first. This would ideally work just like the existing input window.

Use case: When composing longer text in the window, and needing to respond to something immediately, it's easier to click into a second window, without needing to store the text of the main window. 

Example: http://i.imgur.com/LBpdlrI.jpg

**Comment by BeipDev** [comment]
I think you'll agree we've got this one totally solved for the next build! Arbitrary numbers of input panes with different prefixes on each. The trick is just finalizing the syntax on the `/newinput` command.
