### ISSUE TITLE
Add "Copy" to Connect/World screen.

### ISSUE THREAD

**Issue by skewskewskew** [BeipDev/BeipMU#62]
Copy everything for a world as "Copy of <World Name>". This will allow more easily copying settings (such as unicode) and also connection strings for characters.

Yes, we'd have to change the name of characters, but for people on many servers, there's often a lot of things that get copied.

Can it copy triggers, too?

**Comment by BeipDev** [comment]
Gotcha covered! I made it copy everything, characters, triggers, etc... whatever is inside the server should be copied exactly. It will give it a new unique name but that should be expected.

I also made it so you can copy a character too (since it was easy after getting the server to copy).
