### ISSUE TITLE
Incorrect examples in /delay

### ISSUE THREAD

**Issue by skewskewskew** [BeipDev/BeipMU#63]
Input: `/delay`

Output:
ℹ️Usage:
ℹ️  To send a command after a delay: 'delay <time> <command>'
ℹ️  To list currently delayed commands: 'delay list'
ℹ️  To kill an upcoming command: 'delay kill <id>'
ℹ️  For time, the format is: number(h,m,s). 3m = 3 minutes, 10s = 10 seconds, etc.
ℹ️Example: To send 'WHO' after 3 minutes, 'delay 3m "WHO"'

Those samples all need to include a `/` before them. Also, might want to update the ' to ` so it looks like a mark-down appropriate code snippet?

**Comment by BeipDev** [comment]
Ok, I updated it locally to this:

ℹ️Usage:
ℹ️  To send a command after a delay: '/delay <time> <command>'
ℹ️  To list currently delayed commands: '/delay list'
ℹ️  To kill an upcoming command: '/delay kill <id>'
ℹ️  For time, the format is: number(h,m,s). 3m = 3 minutes, 10s = 10 seconds, etc.
ℹ️Example: To send 'WHO' after 3 minutes, '/delay 3m "WHO"'

**Comment by skewskewskew** [comment]
Looks good! Assuming you don't want me to close this until the release comes?
