### ISSUE TITLE
Make a /receive command

### ISSUE THREAD

**Issue by JinxLuckless** [BeipDev/BeipMU#64]
Ideally, I'd love to have a way to make it think it received 'whatever' without bothering me with having to actually send it to the server or at least have it not shown up on my screen, so maybe gagged?

So for example:

"think [Public] This is me opening a spawn window!"

And if that matched my trigger for the spawn, it would open the spawn window without showing me that line as though it had just been 'live.' aka it would gag that line.

I hope I'm making sense. :P I don't care whether or not it actually sends it to the server, as long as the trigger fires to open the spawn window (in this example) and I don't see the 'think' line in my screen. I don't mind if something like, 'Receive message sent.' or something gets sent to me, though.

I'm trying to avoid my own confusion in thinking there's been a message on Public if there hasn't.

**Comment by BeipDev** [comment]
Ok, I have it working like this:

/receive <text>

Is just like: /@window.connection.receive("<text>\r\n");
Basically all text after /receive, plus a newline.

Any quotes, slashes, etc.. don't need to be escaped the same way they would be in the JS. So just paste directly what you want to act like it was received from the server.
