### ISSUE TITLE
Feature: Tab Activates next Input Window

### ISSUE THREAD

**Issue by skewskewskew** [BeipDev/BeipMU#69]
Add an option that when hitting tab (or another keyboard shortcut), you can cycle through input windows (those created by /newinput).

**Comment by BeipDev** [comment]
I ran into a slight issue in doing this one. The tab order is the order the windows were created. But if you rearrange your input panes the tab order might be confusing. Is that okay?

**Comment by BeipDev** [comment]
Do you want a key to go to the previous pane?

**Comment by skewskewskew** [comment]
I think tabbing "out of order" is fine. There's a clear reason for *why* it works that way, and so players will  be able to understand that.

I don't need a "previous" button. Cycling through is fine.
