### ISSUE TITLE
Trackpad Scrolling scrolls too much

### ISSUE THREAD

**Issue by skewskewskew** [BeipDev/BeipMU#71]
When using a (some?) trackpad, using a two-finger scroll moves the screen 20+ lines at a time instead of a few. Usage in other apps (browsers, Windows explorer, etc) is as expected.

**Comment by BeipDev** [comment]
Fixed! The old code would 'snap to the line scroll amount' even if you scrolled a little, so a bunch of tiny scrolls would be amplified to the line scroll amount. Now it does fractional scrolls.
