### ISSUE TITLE
More flexible autolog name arrangement

### ISSUE THREAD

**Issue by Ninjakitten** [BeipDev/BeipMU#75]
More flexibility in automatic log-naming would be great, to allow us to have things like <Game>_<Char>_<AutoDate>o.txt or <Game>_<Char>_<AutoDate>_offscreen.txt or the like if we have a particular naming scheme we use.  You mentioned perhaps using %%date%% in the log name set-up to pull the date format we had set into the appropriate place, and that sounds entirely reasonable to me!

**Comment by BeipDev** [comment]
Ok, %date% implemented!
