### ISSUE TITLE
Separate store-to-history-buffer key-option

### ISSUE THREAD

**Issue by Ninjakitten** [BeipDev/BeipMU#78]
This is one of my 'SimpleMU transplant' wishes. I know that we can use ctrl-down (or whatever we change it to) to go forward through the history window, and that if we're at the bottom of it already, it will put what we have in the input window into the history as if we'd sent it.  What I'd love is the ability to bind that last part, putting what's in input into the history like that, to a different key than the one I use to go forward through the history list.  If ctrl-down still did it the way it does now as well, that shouldn't break it for anyone, I'd think.

(In SimpleMU, back in history was ctrl-p, forward was ctrl-n, and you could pop your pose-in-progress in there with esc. I mapped back to ctrl-p and forward to esc for now, but I keep accidentally opening new windows when I want to go forward in the list. ;) )

**Comment by Ninjakitten** [comment]
So, I know we talked about this a little bit, but I've realised this is actually a different request than I'd been thinking. 

So, here's the use case:

1) I begin typing a pose.
2) Someone says something I need to respond to (a page, ooc, etc)
3) I hit ctrl-down (or my equivalent keybind)
4) What I was writing pops into history, I have an empty input window, and I write and send my response
5) I hit ctrl-up (or my equivalent keybind) twice, and get my pose-in-process back.
6) I continue writing the pose
7) Another thing I need to respond to gets said
8) I hit ctrl-down (OMEK)
9) My input window now holds my response from step 4 (logical when what's really happening here is traversing the stack), when what I expected/want is for what I had to pop itself to 'last item' status in the history stack and for the input window to be empty, just like the first time around.

So, it turns out what I'm **actually** asking about is a second keybind which puts whatever I'm currently writing at the end of the history stack and blanks the input window so I can just start typing.

I know this use can be approximated by having a second input window and using a keybind to switch between them, but that does require having a second input window somewhere on my not-very-large screen, and if I had the choice I'd rather not have to figure out where that could work for me!

**Comment by BeipDev** [comment]
Hmm, would it be better if selecting an item in the history left it 'selected all' in the input window? This way if you ever Ctrl+Down you can start typing and it'll wipe out whatever was there. The same number of steps as stashing to history and getting a blank input window.

How about that? Or are there drawbacks to selecting what's in the input window on history navigation?

**Comment by Ninjakitten** [comment]
The one drawback I see there is that at present, when I've 'paused' a pose, once I call it back to continue, I'm used to just typing from that point, so if the one I **want** is automatically selected-all, I'm likely to continually accidentally erase the thing I was trying to save. I would presumably learn (after a lot of frustration) but it would definitely still require at least one extra keystroke -- right arrow, probably, to get to the end.
