### ISSUE TITLE
End/Split on Page Up interaction

### ISSUE THREAD

**Issue by Ninjakitten** [BeipDev/BeipMU#79]
Split on Page Up is awesome, but sometimes I end up scrolling pretty far up in it to find something, and I don't want to do a long scroll or a lot of Page Down to get back to where I was.  If I hit End, the output window scrolls down to the end just as I'd hope, except that it doesn't cancel the split. It would feel more intuitive if using End when in a Split like that took you down to the end and also got rid of the split, and save an extra Page Down press.

**Comment by BeipDev** [comment]
Fixed, End (Ctrl+End by default) now merges the split too.
