### ISSUE TITLE
Timers IsActive/IsPending

### ISSUE THREAD

**Issue by epsilon-phase** [BeipDev/BeipMU#8]
Timers are nice. That's hard to dispute, but it would be good to have some way to tell if they're active, so you can avoid a trigger starting too many events at once, for example.

**Comment by BeipDev** [comment]
Hah, which method name do you prefer, IsActive() or IsPending()? I slightly lean towards IsActive() but I can go either way

**Comment by epsilon-phase** [comment]
IsActive is probably better, honestly, but it makes more sense for timers, but IsPending makes more sense for timeouts.

**Comment by BeipDev** [comment]
Hmm, I realized I could add it as a property instead of a method. Is a '.active' property ok?

function foo() { window.output.write("Timer hit!"); }
var timer=app.createtimeout(10000, foo);
window.output.write("Timer active:"+foo.active);

**Comment by epsilon-phase** [comment]
I think that sounds fine.
