### ISSUE TITLE
Enh req: option for spawn windows to exclude contents from logs

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#89]
I have several commands for stuff like +who, descs, +finger, and other stuff that is only useful for the moment I'm looking at it and gets spawned out to keep it from cluttering the main screen. 
It would be nice to have a way to have these spawn windows omitted from logs as well.

**Comment by BeipDev** [comment]
I was just poking around near the spawn code again and thought about this one, would a 'Gag from log' option in the spawn window be what you want? (and you could assume captured stuff is gagged too) do everything you wanted? It does overlap a bit with the other 'gag' but I think it makes sense.

**Comment by Seraphiel0** [comment]
Sounds like it would. I envisioned an option on the Spawn tab, but if it's somehow persistent on the window's settings that would work fine.

**Comment by BeipDev** [comment]
Oh! I meant the 'spawn tab' not the 'spawn window'.. so it'll be exactly how you imagined. I didn't think of putting it on the window itself as that won't persist yet.
