### ISSUE TITLE
Spawn window tooltips

### ISSUE THREAD

**Issue by epsilon-phase** [BeipDev/BeipMU#9]
I can't speak as to the situation in Windows, but in Wine on linux, the spawn windows have this tendency to put up the tooltips regardless of your general settings for the output pane.

It'd be nice if they copied those settings, because since Wine doesn't handle closing them properly, they're a real nuisance.

I'd like to think the windows users might like the consistency it would bring too.

**Comment by BeipDev** [comment]
I fixed it so that it'll follow the settings in the main output window. Any changes there will apply to the spawn windows too.
