### ISSUE TITLE
Request for Full Support of Pueblo enhanced MU's

### ISSUE THREAD

**Issue by mrvamps** [BeipDev/BeipMU#90]
In a few other clients, Pueblo is support by using a link style setup. I know that many of the +commands are support in BeipMU, but would be nice to see the same ablities in Beip. MUSHClient is the reference i can give for the idea of support for Pueblo. thanks for looking. Great client so far.

**Comment by DeerInHeadlights2** [comment]
The main tag my favorite game (United Heroes at unitedheroesmush.com:1999) uses is the send tag. Two examples below, one of a simple send with one option, another that implements a right click menu with two choices.  Images from MUSHClient.

Also, when I enable Pueblo in Beipmu on this game, every full line of text from the game gets an extra return on screen for some reason as you can see in the text cut and paste below



**Normal text:**
```
=========================<* United Heroes MUSH BBS  *>==========================
Alias Name                           Member       #Mess #Unrd Perm 
================================< Main Boards >=================================
 1    Official Announcements         Yes           86    0         
```



**Showing tags:**
```
=========================<* United Heroes MUSH BBS  *>==========================

Alias Name                           Member       #Mess #Unrd Perm 

================================< Main Boards >=================================

 <send "+bbread 1" hint="+bbread 1">1    <send "+bbread 1" hint="+bbread 1">Official Announcements         Yes           86    0    
```


**Mouse over image:**
![Pueblo_mouseover1](https://user-images.githubusercontent.com/51407426/58956700-93f07700-8764-11e9-9b48-06d34198b4e3.jpg)






**_Second example with a right click menu of two options:_**


**Normal text**
```
===================================<* Who *>====================================
Name                 Alias       Fac Idle Conn G Made-Up Names                
================================================================================
Andre Jackson        Dre               2h   5d M None             
```            




**Showing tags:**
```
===================================<* Who *>====================================

Name                 Alias       Fac Idle Conn G Made-Up Names                

================================================================================

<send "+finger Andre Jackson|+join Andre Jackson" hint="Right Click for Menu (Default: +finger)|+join">Andre Jackson        Dre               2h   5d M None    
```

**Mouse over image:**
![Pueblo_mouse_over2](https://user-images.githubusercontent.com/51407426/58956512-14fb3e80-8764-11e9-8b01-ed1fb018c92d.JPG)
**Right click image:**
![Pueblo_right_click2](https://user-images.githubusercontent.com/51407426/58956511-14fb3e80-8764-11e9-8625-a9dbe4ec7cfc.JPG)



I also noticed at the login I get the following tag as the first thing received, though I don't notice anything visual associated with it:

<img xch_mode=purehtml><xch_page clear=text>

**Comment by DeerInHeadlights2** [comment]
Heard back from the coder at United Heroes. He said in addition to <SEND>, that the <XCH_CMD> and <A> tags are the main ones in use.   Said it is best to support SEND but his code tries to fall back to Pueblo if it's not supported, but it's kind of ugly.

<a href="http://www.pennmush.org">PennMUSH</a>
