### ISSUE TITLE
Additional options for /connect

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#97]
Additional options for /connect:

* /connect /new /noactivate <server> <character>
       - for the /connect command to open new tabs (instead of reusing the current one, or failing if it's already connected) and opening the tabs in the background.
* /connect (no params) on a disconnected tab to reconnect

**Comment by BeipDev** [comment]
Should we close this one? Just pressing 'Enter' in a disconnected world will do the auto reconnect (I think you learned about that a few days ago), and the restore stuff should take care of the first option!

**Comment by Seraphiel0** [comment]
> Should we close this one? Just pressing 'Enter' in a disconnected world will do the auto reconnect (I think you learned about that a few days ago), and the restore stuff should take care of the first option!

Pressing enter does work, but isn't functionally much different from having to go to each tab and right-click->connect.  It has the added bonus of requiring another keypress to confirm it.  These extra steps are what I was hoping to remove by being able to (for instance) /wall /connect and switch everything back on.

Buuuut yeah if the restore stuff is all working properly then I guess there's not much reason to leave the app open at all, which is how this became an issue in the first place.
