### ISSUE TITLE
Clicking undocked Spawn does not draw focus to Beipmu

### ISSUE THREAD

**Issue by DeerInHeadlights2** [BeipDev/BeipMU#98]
Minor issue. If a Spawn window is undocked outside it's main Beipmu window, then clicking on the Spawn while some non-Beipmu window has focus won't bring the Spawn to the foreground for reading. 

Open Beipmu.  Generate a spawn and drag it outside the window. Open something like Chrome and partially cover Beipmu and the Spawn. Clicking in the Spawn will pause the Spawn but it remains hidden behind Chrome. After clicking, Chrome remains the active application. This happens even if clicking the Spawn title bar.

If you have two Beipmu windows open, clicking in the one that didn't make the Spawn, then the Spawn, will cause the Spawn to move to the foreground. So the Spawn will take focus if any other Beipmu window had it, but not if Chrome/etc had focus.   (Windows 10)

**Comment by BeipDev** [comment]
I think I fixed it, now it calls 'SetForegroundWindow' on the spawn's owner when it attempts to activate
