### ISSUE TITLE
Auto connect order should match Worlds window order

### ISSUE THREAD

**Issue by Seraphiel0** [BeipDev/BeipMU#99]

**Comment by BeipDev** [comment]
This one is now a little tricky with the restore, since it'll re-use the windows in their existing order. Seems complicated to reconnect all restored windows, then sort the remaining ones in alphabetical order but that seems to be what it'd need to do at this point?

**Comment by Seraphiel0** [comment]
This is probably (even) less important now with the restore working. Even before it was just more of a counterintuitive behavior since the worlds were auto-connected in the order they were *made* as that's the order they appeared in the file.
One possible fix is to write the config into that order when the list is reordered, so the existing connection behavior wouldn't need to be changed.

**Comment by BeipDev** [comment]
Closing for now, since the window save/restore fixes the 99% case for this.
